name: Package and Upload to Cloudflare R2

on:
  push:
    branches:
      - main  # 触发动作的分支，可以根据需求调整

jobs:
  package_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the current time
        id: get_time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create a ZIP file
        run: |
          zip -r repository_${{ env.CURRENT_TIME }}.zip .

      - name: Upload to Cloudflare R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_REGION: ${{ secrets.R2_REGION }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
          aws configure set default.region "$R2_REGION"
          
          # 配置自定义端点
          aws configure set default.s3.endpoint_url "$R2_ENDPOINT"

          # 上传文件到指定的 Cloudflare R2 存储桶
          aws s3 cp repository_${{ env.CURRENT_TIME }}.zip s3://${{ env.R2_BUCKET_NAME }}/repository_${{ env.CURRENT_TIME }}.zip
