name: Package and Upload to Cloudflare R2

on:
  push:
    branches:
      - main  # 触发动作的分支，可以根据需求调整

jobs:
  package_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the current time
        id: get_time
        run: echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create a ZIP file
        run: |
          zip -r repository_${{ env.CURRENT_TIME }}.zip .

      - name: Upload to Cloudflare R2
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.R2_BUCKET_NAME }}
          file: ./repository_${{ env.CURRENT_TIME }}.zip
          destination: '/Maa_Update'
