name: Sync Repository

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  sync-repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: 'https://github.com/MaaAssistantArknights/MaaResource'  # 替换为源仓库的URL
        ref: 'main'  # 如果需要同步特定的分支，在这里修改
        token: '${{ secrets.ACCESS_TOKEN }}'  # 用于访问源仓库的访问令牌

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Pull Changes from Source Repository
      run: git pull --ff-only

    - name: Push Changes to Current Repository
      run: git push
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 用于推送更改的访问令牌
